// <auto-generated />
using System;
using AXLSmartRepository.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AXLSmartWebAPI.Migrations
{
    [DbContext(typeof(PlutoContext))]
    [Migration("20220503101109_05-03-2022-Add_AppointmentDetails")]
    partial class _05032022Add_AppointmentDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("AXLSmartRepository.Core.Models.ApplicationPlanAndAccomplishment", b =>
                {
                    b.Property<Guid>("apaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonForNonAccomplish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WorkplaceAppicationPlanwapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("catchUpActivities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateAssessed")
                        .HasColumnType("datetime2");

                    b.Property<string>("meansOfVerification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("milestone")
                        .HasColumnType("int");

                    b.Property<int>("progress")
                        .HasColumnType("int");

                    b.Property<DateTime?>("targetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("whatNeedsToBeDone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whatWasDone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whatWasNotDone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("apaId");

                    b.HasIndex("WorkplaceAppicationPlanwapId");

                    b.ToTable("ApplicationPlanAndAccomplishments");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.AppointmentDetail", b =>
                {
                    b.Property<Guid>("appointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("changePersonStatus")
                        .HasColumnType("int");

                    b.Property<string>("employeeEmailAdrs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("existingSalaryGrade")
                        .HasColumnType("int");

                    b.Property<decimal>("finalRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("has_case_offense")
                        .HasColumnType("bit");

                    b.Property<bool>("is_renew_contract")
                        .HasColumnType("bit");

                    b.Property<decimal>("performanceEval")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("personId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("proposedSalaryGrade")
                        .HasColumnType("int");

                    b.Property<decimal>("wapRating")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("appointmentId");

                    b.ToTable("AppointmentDetails");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.AppointmentList_vw", b =>
                {
                    b.Property<string>("appointeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("appointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("finalRating")
                        .HasColumnType("decimal(18,2)");

                    b.ToView("AppointmentList_vw");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.BudgetUtilizationDetail", b =>
                {
                    b.Property<Guid>("budgetUtilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("amountSpentQ1JO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("amountSpentQ1Plantil")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("amountSpentQ2JO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("amountSpentQ2Plantil")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("amountSpentQ3JO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("amountSpentQ3Plantil")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("amountSpentQ4JO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("amountSpentQ4Plantil")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("is_funding_set_aside")
                        .HasColumnType("bit");

                    b.Property<decimal>("totalBudgetJO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("totalBudgetPlantil")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("with_additional_proposed_budget")
                        .HasColumnType("int");

                    b.Property<int>("with_last_year_proposed_budget")
                        .HasColumnType("int");

                    b.HasKey("budgetUtilId");

                    b.ToTable("BudgetUtilizationDetails");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.BudgetUtilizationList_vw", b =>
                {
                    b.Property<Guid>("budgetUtilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("is_funding_set_aside")
                        .HasColumnType("bit");

                    b.Property<decimal>("totalBudgetJO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("totalBudgetPlantil")
                        .HasColumnType("decimal(18,2)");

                    b.ToView("BudgetUtilizationList_vw");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.ClearanceDetail", b =>
                {
                    b.Property<Guid>("clearanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("dateOfApplication")
                        .HasColumnType("datetime2");

                    b.Property<string>("deleted_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("divisionHead")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("effectivityInclusivePeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("immediateSupervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isLeave")
                        .HasColumnType("bit");

                    b.Property<bool?>("isOther")
                        .HasColumnType("bit");

                    b.Property<bool?>("isResignation")
                        .HasColumnType("bit");

                    b.Property<bool?>("isRetirement")
                        .HasColumnType("bit");

                    b.Property<bool?>("isTransfer")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("personId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("specifyOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("withOnGoingInvestigation")
                        .HasColumnType("bit");

                    b.Property<bool?>("withPendingAdminCase")
                        .HasColumnType("bit");

                    b.HasKey("clearanceId");

                    b.ToTable("Clearances");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.ClearanceList_vw", b =>
                {
                    b.Property<Guid>("clearanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dateOfApplication")
                        .HasColumnType("datetime2");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("ClearanceList_vw");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.ComplaintDetail", b =>
                {
                    b.Property<Guid>("complaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("complaineeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("complaineeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("complaintName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("emailAddressComplainant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailAddressSupervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("grievanceDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("officeId")
                        .HasColumnType("int");

                    b.Property<Guid>("personId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("typeOfComplaint")
                        .HasColumnType("int");

                    b.HasKey("complaintId");

                    b.ToTable("ComplaintDetails");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.ComplaintList_vw", b =>
                {
                    b.Property<Guid>("complaintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("complaintName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("officeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeOfComplaint")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("ComplaintList_vw");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.HRStaffingPlanDetail", b =>
                {
                    b.Property<Guid>("hrStaffingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("deleted_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("existingNosPersonnelJO")
                        .HasColumnType("int");

                    b.Property<int>("existingNosPersonnelPlantil")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("nosFilledPosJO")
                        .HasColumnType("int");

                    b.Property<int>("nosFilledPosPlantil")
                        .HasColumnType("int");

                    b.Property<int>("nosProposedPosToChangeJO")
                        .HasColumnType("int");

                    b.Property<int>("nosProposedPosToChangePlantil")
                        .HasColumnType("int");

                    b.Property<int>("nosUnfilledPosJO")
                        .HasColumnType("int");

                    b.Property<int>("nosUnfilledPosPlantil")
                        .HasColumnType("int");

                    b.Property<int>("proposedNosPersonnelNextYrJO")
                        .HasColumnType("int");

                    b.Property<int>("proposedNosPersonnelNextYrPlantil")
                        .HasColumnType("int");

                    b.HasKey("hrStaffingId");

                    b.ToTable("HRStaffingPlanDetails");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.HRStaffingPlanList_vw", b =>
                {
                    b.Property<int>("existingNosPersonnelJO")
                        .HasColumnType("int");

                    b.Property<int>("existingNosPersonnelPlantil")
                        .HasColumnType("int");

                    b.Property<Guid>("hrStaffingId")
                        .HasColumnType("uniqueidentifier");

                    b.ToView("HRStaffingPlanList_vw");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.JobClassification", b =>
                {
                    b.Property<int>("jobClassificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("classCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("classDesc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("occupationalDesc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("occupationalGrpCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("occupationalGrpDesc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("occupationalServCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("salary_grade")
                        .HasColumnType("int");

                    b.HasKey("jobClassificationId");

                    b.ToTable("JobClassifications");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.JobRequisition", b =>
                {
                    b.Property<Guid>("requisitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("closingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("deleted_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.Property<bool>("isApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("isOpen")
                        .HasColumnType("bit");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("jobCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("jobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("locationAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("requestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("requestTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("requisitionId");

                    b.ToTable("JobRequisitions");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.JobRequisitionList_vw", b =>
                {
                    b.Property<DateTime>("closingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("department_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("isOpen")
                        .HasColumnType("bit");

                    b.Property<string>("jobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job_category_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("locationAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("requestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("request_type_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("requisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.ToView("JobRequisitionList_vw");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.LDNAConsolidated_sp", b =>
                {
                    b.Property<string>("CompetencyCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoreCompetency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("District_Provincial_Health_Teams_Contractual")
                        .HasColumnType("int");

                    b.Property<int>("District_Provincial_Health_Teams_Permanent")
                        .HasColumnType("int");

                    b.Property<int>("PMED_Contractual")
                        .HasColumnType("int");

                    b.Property<int>("PMED_Permanent")
                        .HasColumnType("int");

                    b.Property<int>("Regulation_Licensing_and_Enforcement_Division_Contractual")
                        .HasColumnType("int");

                    b.Property<int>("Regulation_Licensing_and_Enforcement_Division_Permanent")
                        .HasColumnType("int");

                    b.ToView("LDNAResult_sp");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.LDNADetails", b =>
                {
                    b.Property<Guid>("ldnaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.HasKey("ldnaId");

                    b.ToTable("LDNADetails");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.LDNAResults", b =>
                {
                    b.Property<Guid>("ldnaResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LDNADetailsldnaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("competencyId")
                        .HasColumnType("int");

                    b.Property<int>("contractual")
                        .HasColumnType("int");

                    b.Property<int>("coreCompetencyId")
                        .HasColumnType("int");

                    b.Property<int>("permanent")
                        .HasColumnType("int");

                    b.HasKey("ldnaResultId");

                    b.HasIndex("LDNADetailsldnaId");

                    b.ToTable("LDNAResults");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.OrganizationalGoalDetail", b =>
                {
                    b.Property<Guid>("orgGoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("deleted_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("mandateOfOffice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("missionOfOffice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stratigicGoalsOfOffice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("visionOfOffice")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("orgGoalId");

                    b.ToTable("OrganizationalGoalDetails");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.OrganizationalGoalList_vw", b =>
                {
                    b.Property<string>("missionOfOffice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("orgGoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("visionOfOffice")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("OrganizationalGoalList_vw");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PES11Detail", b =>
                {
                    b.Property<Guid>("pes11Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("avgPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("grandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("immediateSupPosition")
                        .HasColumnType("int");

                    b.Property<string>("immediateSupervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("personId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("reviewPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("scr_askForHelp")
                        .HasColumnType("int");

                    b.Property<int?>("scr_balancesTeam")
                        .HasColumnType("int");

                    b.Property<int?>("scr_competent")
                        .HasColumnType("int");

                    b.Property<int?>("scr_complianceToOffice")
                        .HasColumnType("int");

                    b.Property<int?>("scr_contribute")
                        .HasColumnType("int");

                    b.Property<int?>("scr_courtesy")
                        .HasColumnType("int");

                    b.Property<int?>("scr_creativity")
                        .HasColumnType("int");

                    b.Property<int?>("scr_designsWorkflows")
                        .HasColumnType("int");

                    b.Property<int?>("scr_devInnovateIdeas")
                        .HasColumnType("int");

                    b.Property<int?>("scr_displaysUnderstanding")
                        .HasColumnType("int");

                    b.Property<int?>("scr_diverseInfo")
                        .HasColumnType("int");

                    b.Property<int?>("scr_exhibitAbility")
                        .HasColumnType("int");

                    b.Property<int?>("scr_exhibitsGoodListening")
                        .HasColumnType("int");

                    b.Property<int?>("scr_exhibitsObjective")
                        .HasColumnType("int");

                    b.Property<int?>("scr_expressesIdeas")
                        .HasColumnType("int");

                    b.Property<int?>("scr_humanRelations")
                        .HasColumnType("int");

                    b.Property<int?>("scr_identifiesData")
                        .HasColumnType("int");

                    b.Property<int?>("scr_improveWork")
                        .HasColumnType("int");

                    b.Property<int?>("scr_integratesChanges")
                        .HasColumnType("int");

                    b.Property<int?>("scr_integrity")
                        .HasColumnType("int");

                    b.Property<int?>("scr_keepsAbreast")
                        .HasColumnType("int");

                    b.Property<int?>("scr_keepsOtherAdequate")
                        .HasColumnType("int");

                    b.Property<int?>("scr_minimalSupervision")
                        .HasColumnType("int");

                    b.Property<int?>("scr_plansForAddResources")
                        .HasColumnType("int");

                    b.Property<int?>("scr_plansWorkAct")
                        .HasColumnType("int");

                    b.Property<int?>("scr_presenDataEff")
                        .HasColumnType("int");

                    b.Property<int?>("scr_punctuality")
                        .HasColumnType("int");

                    b.Property<int?>("scr_putsSuccess")
                        .HasColumnType("int");

                    b.Property<int?>("scr_researchesData")
                        .HasColumnType("int");

                    b.Property<int?>("scr_resourceful")
                        .HasColumnType("int");

                    b.Property<int?>("scr_seekIncResponsibilities")
                        .HasColumnType("int");

                    b.Property<int?>("scr_setsGoals")
                        .HasColumnType("int");

                    b.Property<int?>("scr_stressTolerance")
                        .HasColumnType("int");

                    b.Property<int?>("scr_takeIndActions")
                        .HasColumnType("int");

                    b.Property<int?>("scr_takesAdvantage")
                        .HasColumnType("int");

                    b.Property<int?>("scr_undertakeSelfDev")
                        .HasColumnType("int");

                    b.Property<int?>("scr_usesAppCom")
                        .HasColumnType("int");

                    b.Property<int?>("scr_usesIntuition")
                        .HasColumnType("int");

                    b.Property<int?>("scr_usesResources")
                        .HasColumnType("int");

                    b.Property<int?>("scr_usesTimeEff")
                        .HasColumnType("int");

                    b.Property<int?>("scr_volunteersReadily")
                        .HasColumnType("int");

                    b.Property<int?>("scr_welcomesFeedback")
                        .HasColumnType("int");

                    b.Property<int?>("scr_worksOrganizedManner")
                        .HasColumnType("int");

                    b.Property<int?>("scr_writesClearly")
                        .HasColumnType("int");

                    b.HasKey("pes11Id");

                    b.ToTable("PES11s");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PES11List_vw", b =>
                {
                    b.Property<decimal>("avgPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("grandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("pes11Id")
                        .HasColumnType("uniqueidentifier");

                    b.ToView("PES11List_vw");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PersonDetail", b =>
                {
                    b.Property<Guid>("personId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("blood_type_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brgy_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("citizenship_id")
                        .HasColumnType("int");

                    b.Property<string>("city_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("civil_status_id")
                        .HasColumnType("int");

                    b.Property<string>("deleted_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("extName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pagIbig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("philHealth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placeOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prov_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("purok")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sex")
                        .HasColumnType("int");

                    b.Property<string>("sss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personId");

                    b.ToTable("PersonDetails");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PersonEducation", b =>
                {
                    b.Property<Guid>("personEducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonDetailpersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("degreeCourse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("highestAttaind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("nameOfSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scholarshipAwardHonor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("schoolLevelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("yearGraduated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personEducationId");

                    b.HasIndex("PersonDetailpersonId");

                    b.ToTable("PersonEducations");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PersonEligibility", b =>
                {
                    b.Property<Guid>("personEligibilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonDetailpersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dateOfExamination")
                        .HasColumnType("datetime2");

                    b.Property<string>("deleted_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("eligibilityTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("licensceReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("licenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placeOfExamination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.HasKey("personEligibilityId");

                    b.HasIndex("PersonDetailpersonId");

                    b.ToTable("PersonEligibilities");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PersonFamily", b =>
                {
                    b.Property<Guid>("personFamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonDetailpersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("businessAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("employer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("extName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("relationship")
                        .HasColumnType("int");

                    b.Property<string>("telNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personFamilyId");

                    b.HasIndex("PersonDetailpersonId");

                    b.ToTable("PersonFamilies");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PersonList_vw", b =>
                {
                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("blood_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("citizenship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("civil_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("extName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("personId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("placeOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("PersonList_vw");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PersonTraining", b =>
                {
                    b.Property<Guid>("personTrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonDetailpersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("conductedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("deleted_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("numHours")
                        .HasColumnType("int");

                    b.Property<Guid>("personId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("seminarTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personTrainingId");

                    b.HasIndex("PersonDetailpersonId");

                    b.ToTable("PersonTrainings");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PersonWorkExperience", b =>
                {
                    b.Property<Guid>("personWorkExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonDetailpersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("appointmentStatusId")
                        .HasColumnType("int");

                    b.Property<string>("companyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isGovt")
                        .HasColumnType("bit");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("monthlySalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("positionTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salaryGrade")
                        .HasColumnType("int");

                    b.Property<int>("salaryStep")
                        .HasColumnType("int");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("personWorkExperienceId");

                    b.HasIndex("PersonDetailpersonId");

                    b.ToTable("PersonWorkExperiences");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.User", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("deleted_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("hash_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_level")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.UserList_vw", b =>
                {
                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_level")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("UserList_vw");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.WorkplaceAppicationPlan", b =>
                {
                    b.Property<Guid>("wapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonDetailspersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("alignment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date_conduct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("learningOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("objective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("output")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("wapId");

                    b.HasIndex("PersonDetailspersonId");

                    b.ToTable("WorkplaceAppicationPlans");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.WorkplaceApplicationPlan_vw", b =>
                {
                    b.Property<DateTime>("date_conduct")
                        .HasColumnType("datetime2");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("personId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("wapId")
                        .HasColumnType("uniqueidentifier");

                    b.ToView("WorkplaceApplicationPlan_vw");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_blood_type", b =>
                {
                    b.Property<int>("blood_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("blood_type_id");

                    b.ToTable("Lib_Blood_Types");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_brgy", b =>
                {
                    b.Property<string>("brgy_code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("brgy_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rowid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("sortOrder")
                        .HasColumnType("int");

                    b.HasKey("brgy_code");

                    b.ToTable("Lib_Barangays");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_citizenship", b =>
                {
                    b.Property<int>("citizenship_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("citizenship_id");

                    b.ToTable("Lib_Citizenships");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_city", b =>
                {
                    b.Property<string>("city_code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("city_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prov_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rowid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("sortOrder")
                        .HasColumnType("int");

                    b.HasKey("city_code");

                    b.ToTable("Lib_Cities");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_civil_status", b =>
                {
                    b.Property<int>("civil_status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("civil_status_id");

                    b.ToTable("Lib_Civil_Statuses");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_competency_category", b =>
                {
                    b.Property<int>("competencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<int?>("lib_core_competencycoreCompetencyId")
                        .HasColumnType("int");

                    b.HasKey("competencyId");

                    b.HasIndex("lib_core_competencycoreCompetencyId");

                    b.ToTable("Lib_Competency_Categories");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_core_competency", b =>
                {
                    b.Property<int>("coreCompetencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.HasKey("coreCompetencyId");

                    b.ToTable("Lib_Core_Competencies");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_department", b =>
                {
                    b.Property<int>("departmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.HasKey("departmentId");

                    b.ToTable("Lib_Departments");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_job_category", b =>
                {
                    b.Property<int>("jobCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.HasKey("jobCategoryId");

                    b.ToTable("Lib_Job_Categories");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_occupational_group_code", b =>
                {
                    b.Property<string>("occupational_grp_code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.HasKey("occupational_grp_code");

                    b.ToTable("Lib_Occupational_Group_Codes");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_occupational_service_code", b =>
                {
                    b.Property<string>("occupational_serv_code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.HasKey("occupational_serv_code");

                    b.ToTable("Lib_Occupational_Service_Codes");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_province", b =>
                {
                    b.Property<string>("prov_code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("prov_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rowid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("sortOrder")
                        .HasColumnType("int");

                    b.HasKey("prov_code");

                    b.ToTable("Lib_Provinces");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_region", b =>
                {
                    b.Property<string>("region_code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("region_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rowid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("sortOrder")
                        .HasColumnType("int");

                    b.HasKey("region_code");

                    b.ToTable("Lib_Regions");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_request_type", b =>
                {
                    b.Property<int>("requestTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.HasKey("requestTypeId");

                    b.ToTable("Lib_Request_Types");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_user_level", b =>
                {
                    b.Property<int>("userLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.HasKey("userLevelId");

                    b.ToTable("Lib_User_Levels");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.ApplicationPlanAndAccomplishment", b =>
                {
                    b.HasOne("AXLSmartRepository.Core.Models.WorkplaceAppicationPlan", null)
                        .WithMany("ApplicationPlanAndAccomplishments")
                        .HasForeignKey("WorkplaceAppicationPlanwapId");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.LDNAResults", b =>
                {
                    b.HasOne("AXLSmartRepository.Core.Models.LDNADetails", null)
                        .WithMany("ldnaResults")
                        .HasForeignKey("LDNADetailsldnaId");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PersonEducation", b =>
                {
                    b.HasOne("AXLSmartRepository.Core.Models.PersonDetail", null)
                        .WithMany("personEducations")
                        .HasForeignKey("PersonDetailpersonId");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PersonEligibility", b =>
                {
                    b.HasOne("AXLSmartRepository.Core.Models.PersonDetail", null)
                        .WithMany("personEligibilities")
                        .HasForeignKey("PersonDetailpersonId");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PersonFamily", b =>
                {
                    b.HasOne("AXLSmartRepository.Core.Models.PersonDetail", null)
                        .WithMany("personFamily")
                        .HasForeignKey("PersonDetailpersonId");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PersonTraining", b =>
                {
                    b.HasOne("AXLSmartRepository.Core.Models.PersonDetail", null)
                        .WithMany("personTrainings")
                        .HasForeignKey("PersonDetailpersonId");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PersonWorkExperience", b =>
                {
                    b.HasOne("AXLSmartRepository.Core.Models.PersonDetail", null)
                        .WithMany("personWorkExperiences")
                        .HasForeignKey("PersonDetailpersonId");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.WorkplaceAppicationPlan", b =>
                {
                    b.HasOne("AXLSmartRepository.Core.Models.PersonDetail", "PersonDetails")
                        .WithMany()
                        .HasForeignKey("PersonDetailspersonId");

                    b.Navigation("PersonDetails");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_competency_category", b =>
                {
                    b.HasOne("AXLSmartRepository.Core.Models.lib_core_competency", null)
                        .WithMany("libCompetencyCategory")
                        .HasForeignKey("lib_core_competencycoreCompetencyId");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.LDNADetails", b =>
                {
                    b.Navigation("ldnaResults");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.PersonDetail", b =>
                {
                    b.Navigation("personEducations");

                    b.Navigation("personEligibilities");

                    b.Navigation("personFamily");

                    b.Navigation("personTrainings");

                    b.Navigation("personWorkExperiences");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.WorkplaceAppicationPlan", b =>
                {
                    b.Navigation("ApplicationPlanAndAccomplishments");
                });

            modelBuilder.Entity("AXLSmartRepository.Core.Models.lib_core_competency", b =>
                {
                    b.Navigation("libCompetencyCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
